### ISSUE TITLE
Group with many participants disconnects the api

### ISSUE THREAD

**Issue by Goddino-Repo** [Auties00/Cobalt#266]
Sono con la versione 3.3.1, utilizzo il vostro framework senza problemi, tranne in un caso...
Facendo dei test in un gruppo con 3 partecipanti funziona regolarmente, quando però ho provato ad utilizzarlo su un gruppo con 210 partecipanti, qualunque messaggio provo ad inviare, si scollega senza mandare alcuna eccezione

aggiungendo un listener inline:
`.addDisconnectedListener(reason -> System.out.printf("Disconnected: %s%n", reason))`

mi ritrovo solo questa informazione:
`Disconnected: DISCONNECTED`

non ho provato con altri gruppi

Utilizzo il webBuilder

**Comment by Goddino-Repo** [comment]
con la build di maven ottengo il seguente output se può essere utile:

> [[1;33mWARNING[m] thread Thread[ForkJoinPool.commonPool-worker-1,5,com.config.Init] was interrupted but is still alive after waiting at least 15000msecs
[[1;33mWARNING[m] thread Thread[ForkJoinPool.commonPool-worker-1,5,com.config.Init] will linger despite being asked to die via interruption
[[1;33mWARNING[m] thread Thread[ForkJoinPool.commonPool-worker-2,5,com.config.Init] will linger despite being asked to die via interruption
[[1;33mWARNING[m] thread Thread[ForkJoinPool.commonPool-worker-3,5,com.config.Init] will linger despite being asked to die via interruption
[[1;33mWARNING[m] thread Thread[CompletableFutureDelayScheduler,5,com.config.Init] will linger despite being asked to die via interruption
[[1;33mWARNING[m] NOTE: 4 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[[1;33mWARNING[m] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.config.Init,maxpri=10]
[1;31mjava.lang.IllegalThreadStateException[m
    [1mat[m java.lang.ThreadGroup.destroy ([1mThreadGroup.java:803[m)
    [1mat[m org.codehaus.mojo.exec.ExecJavaMojo.execute ([1mExecJavaMojo.java:321[m)
    [1mat[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo ([1mDefaultBuildPluginManager.java:137[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:210[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:156[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:148[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:56[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:305[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:192[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:105[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:957[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:289[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:193[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:77[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:568[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:282[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:225[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:406[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:347[m)
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;32mBUILD SUCCESS[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  01:26 min
[[1;34mINFO[m] Finished at: 2023-04-27T17:29:45Z
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m

**Comment by Goddino-Repo** [comment]
sono riuscito ad ottenere uno stack trace:
`apr 29, 2023 1:03:44 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at UNKNOWN
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2480)
	at it.auties.whatsapp4j/it.auties.whatsapp.util.OrderedAsyncTaskRunner.cancel(OrderedAsyncTaskRunner.java:19)
	at it.auties.whatsapp4j/it.auties.whatsapp.socket.MessageHandler.dispose(MessageHandler.java:904)
	at it.auties.whatsapp4j/it.auties.whatsapp.socket.SocketHandler.dispose(SocketHandler.java:756)
	at it.auties.whatsapp4j/it.auties.whatsapp.socket.SocketHandler.onShutdown(SocketHandler.java:112)
	at it.auties.whatsapp4j/it.auties.whatsapp.socket.SocketHandler.onClose(SocketHandler.java:179)
	at it.auties.whatsapp4j/it.auties.whatsapp.socket.SocketSession.closeResources(SocketSession.java:159)
	at it.auties.whatsapp4j/it.auties.whatsapp.socket.SocketSession.lambda$close$2(SocketSession.java:90)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
	... 16 more
apr 29, 2023 1:03:44 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Ignored failure
Disconnected from the target VM, address: '127.0.0.1:52576', transport: 'socket'`

**Comment by Auties00** [comment]
> 

hai un invito con un gruppo del genere cosi posso testare?

**Comment by Goddino-Repo** [comment]
> > 
> 
> hai un invito con un gruppo del genere cosi posso testare?

Ti giro il mio:
https://chat.whatsapp.com/HfEaERNLIaJBSZUCMtHU8D

**Comment by Goddino-Repo** [comment]
@Auties00 ho provato a buildare dopo la tua ultima commit, ma mi restituisce un errore nella target directory
`C:\Users\Utente\Desktop\Whatsapp4j\target\generated-sources\annotations\it\auties\protobuf\ProtobufStubs.java:3:120937
java: incompatible types: invalid method reference
    incompatible types: java.util.Map cannot be converted to java.util.Collection<it.auties.whatsapp.model.chat.GroupParticipant>`

**Comment by Auties00** [comment]
prova di nuovo, dovrebbe essere risolto @Goddino-Repo

**Comment by Goddino-Repo** [comment]
@Auties00 vedo se ho qualcuno disponibile, nel caso provo sta sera e ti do un feed

**Comment by Goddino-Repo** [comment]
@Auties00 non è testabile, in fase di build mi da questo problema:
https://github.com/Auties00/Whatsapp4j/issues/290
non riesco ad arrivarci
si apre la connessione, caccia eccezione e si chiude il processo

**Comment by Auties00** [comment]
> @Auties00 non è testabile, in fase di build mi da questo problema:
> https://github.com/Auties00/Whatsapp4j/issues/290
> non riesco ad arrivarci
> si apre la connessione, caccia eccezione e si chiude il processo

prova con la versione 3.4.1

**Comment by Goddino-Repo** [comment]
@Auties00 cambiato nulla

```
mag 24, 2023 12:44:22 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at UNKNOWN
java.io.UncheckedIOException: Cannot create link between store and phone number
	at it.auties.whatsapp.controller.DefaultControllerSerializer.linkPhoneNumber(DefaultControllerSerializer.java:264)
	at it.auties.whatsapp.controller.Controller.phoneNumber(Controller.java:98)
	at it.auties.whatsapp.socket.StreamHandler.saveCompanion(StreamHandler.java:851)
	at it.auties.whatsapp.socket.StreamHandler.confirmQrCode(StreamHandler.java:801)
	at it.auties.whatsapp.socket.StreamHandler.digestIq(StreamHandler.java:759)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:87)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:188)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.nio.file.FileSystemException: C:\Users\Utente\.whatsapp4j\web\+39349*******: Il privilegio richiesto non appartiene al client
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:598)
	at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1069)
	at it.auties.whatsapp.controller.DefaultControllerSerializer.linkPhoneNumber(DefaultControllerSerializer.java:262)
	... 13 more
mag 24, 2023 12:44:22 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Ignored failure
Connected
mag 24, 2023 12:44:23 PM com.config.Core onLoggedIn
INFO: Logged in!
mag 24, 2023 12:44:23 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at MESSAGE
java.util.concurrent.CompletionException: it.auties.protobuf.base.ProtobufSerializationException: Cannot invoke "Object.getClass()" because "object" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: it.auties.protobuf.base.ProtobufSerializationException: Cannot invoke "Object.getClass()" because "object" is null
	at it.auties.whatsapp.util.Protobuf.writeMessage(Protobuf.java:22)
	at it.auties.whatsapp.socket.MessageHandler.createEncodedMessageNode(MessageHandler.java:201)
	at it.auties.whatsapp.socket.MessageHandler.lambda$encodeConversation$13(MessageHandler.java:166)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "object" is null
	at it.auties.whatsapp.util.Protobuf.writeMessage(Protobuf.java:19)
	... 9 more
mag 24, 2023 12:44:23 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Ignored failure
Disconnected: LOGGED_OUT

Process finished with exit code 0
```

**Comment by Goddino-Repo** [comment]
@Auties00 ti confermo che ho cambiato versione
pom:
```xml
<dependency>
    <groupId>com.github.auties00</groupId>
    <artifactId>whatsappweb4j</artifactId>
    <version>3.4.1</version>
</dependency>
```

E che ho cancellato tutto il contenuto della directory .whatsapp4j
In più ho utilizzato il builder con `newConnection()` per assicurarmi che non possano esserci stati problemi
Ho compilato e si rompe con l'errore sopra citato

**Comment by jandreotti** [comment]
same problem here. Using last version. 3.4.1

**Comment by Goddino-Repo** [comment]
@Auties00 come ti ho accennato su Discord, compilando come amministratore funziona
Il problema è che se provo a far inviare un messaggio in un gruppo, mi tira eccezione

```
mag 24, 2023 7:08:02 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at MESSAGE
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
    at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException
    at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.addAll(ConcurrentHashMap.java:4747)
    at it.auties.whatsapp.socket.SocketHandler.handleGroupMetadata(SocketHandler.java:484)
    at it.auties.whatsapp.socket.SocketHandler.lambda$queryGroupMetadata$19(SocketHandler.java:472)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
    ... 7 more
mag 24, 2023 7:08:02 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Ignored failure
```

**Comment by jandreotti** [comment]
Same to me. Like admin works. But not working the message to groups

**Comment by Auties00** [comment]
> @Auties00 come ti ho accennato su Discord, compilando come amministratore funziona Il problema è che se provo a far inviare un messaggio in un gruppo, mi tira eccezione
> 
> ```
> mag 24, 2023 7:08:02 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> SEVERE: Socket failure at MESSAGE
> java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException
>     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
>     at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
>     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
>     at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
>     at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
>     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
>     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
>     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
>     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
>     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Caused by: java.lang.UnsupportedOperationException
>     at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.addAll(ConcurrentHashMap.java:4747)
>     at it.auties.whatsapp.socket.SocketHandler.handleGroupMetadata(SocketHandler.java:484)
>     at it.auties.whatsapp.socket.SocketHandler.lambda$queryGroupMetadata$19(SocketHandler.java:472)
>     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
>     ... 7 more
> mag 24, 2023 7:08:02 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> WARNING: Ignored failure
> ```

usa il master

**Comment by Goddino-Repo** [comment]
@Auties00 con l'ultima commit il problema è stato risolto

**Comment by Auties00** [comment]
> @Auties00 con l'ultima commit il problema è stato risolto

benissimo
