### ISSUE TITLE
Stream error reason=405

### ISSUE THREAD

**Issue by wlp7662973** [Auties00/Cobalt#319]
version 3.4.4 and master src code
java.lang.RuntimeException: Stream error: Node[description=failure, attributes={reason=405, location=odn}]
at it.auties.whatsapp.socket.StreamHandler.digestFailure(StreamHandler.java:116)
at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:90)
at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:190)
at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
jun 06, 2023 5:46:49 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1

**Comment by lollix91** [comment]
Same error, with version 3.4.4

SEVERE: Socket failure at STREAM
java.lang.RuntimeException: Stream error: Node[description=failure, attributes={reason=405, location=atn}]
	at it.auties.whatsapp.socket.StreamHandler.digestFailure(StreamHandler.java:116)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:90)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:190)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Auties00** [comment]
web or mobile api?

**Comment by lollix91** [comment]
Web Api. it starts apparently random, especially during login with a previously saved connection.

**Comment by lollix91** [comment]
I'm using the same credentials I were with the other versions. I am usually able to login with these.

**Comment by Auties00** [comment]
Fixed in 3.4.5, reopen if there's still an issue
