### ISSUE TITLE
Hello, is it possible to integrate with Spring Boot? 

### ISSUE THREAD

**Issue by koalsky** [Auties00/Cobalt#324]
HI @Auties00 @angleto 

Why is there no response after I integrate it with Spring Boot, with only a timeout message being displayed?
Looking forward to your reply, thank you.

**Comment by koalsky** [comment]
`@RestController
public class DemoController {

    @GetMapping("/hello")
    public String get() {
        try {
            Whatsapp whatsapp = Whatsapp.webBuilder().newConnection().qrHandler(QrHandler.toFile(QrHandler.ToFileConsumer.toDesktop())).build();
            whatsapp
                    .addLoggedInListener(app -> {
                        System.out.println("ok");
                    })
                    .addNewMessageListener((info) -> {
                        System.err.println(info.message().content());
                    })
                    .addDisconnectedListener((app, reason) -> {
                        System.out.printf("Disconnected: %s%n", reason);
                    })
                    .connect().get(30, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
            System.err.println("InterruptedException-->");
            e.printStackTrace();
        } catch (ExecutionException e) {
            System.err.println("ExecutionException-->");
            e.printStackTrace();
        } catch (TimeoutException e) {
            System.err.println("TimeoutException-->");
            e.printStackTrace();
        }
        return "ok";
    }
}`

**Comment by koalsky** [comment]
TimeoutException-->
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at com.example.demo001.DemoController.get(DemoController.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jandreotti** [comment]
Hello My Friend.  there are a lot of persons that want to use this library with spring boot and are having problems. Maybe Auties may do some example and keep it actualized...

Try this:

pom.xml (there is a problem with the version of  the jackson library, so you need to specify exactly the version 2.14.0. If you use the 2.15.0 that put springboot by default it will give you error):
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.0</version>
        <relativePath/> 
    </parent>
    <groupId>ar.com.orcos.springcloud.orcoswsp</groupId>
    <artifactId>orcos-wsp</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>orcoswsp</name>
    <description>orcoswsp</description>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>whatsappweb4j</artifactId>
            <version>3.4.1</version>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.14.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.14.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.14.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-smile</artifactId>
            <version>2.14.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>2.14.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.14.0</version>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <release>17</release>
                    <compilerArgument>--enable-preview</compilerArgument>
                    <compilerArgs>--enable-preview</compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>
`


Declare a bean some configurator file in a java class and connect it some way:

`
import it.auties.whatsapp.api.*;
import it.auties.whatsapp.controller.DefaultControllerSerializer;
import it.auties.whatsapp.listener.Listener;
import it.auties.whatsapp.model.contact.Contact;
import it.auties.whatsapp.model.info.MessageInfo;
import it.auties.whatsapp.model.message.standard.TextMessage;
import it.auties.whatsapp.model.request.Node;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.nio.file.Path;
import java.util.Collection;

@Configuration
public class WspConfig {


    @Bean
    public Whatsapp whatsappApi() {
        System.out.println("WspConfig.wsp()");

        Whatsapp wsp =
                Whatsapp
                        .webBuilder()
                        .serializer(new DefaultControllerSerializer(Path.of("C:\\Users\\Joaquin\\Desktop\\whatsapp4j")))
                        .lastConnection()
                        .errorHandler(ErrorHandler.toTerminal())

                        .qrHandler(QrHandler.toTerminal())

//                        .qrHandler(qr -> {
//                            System.out.println("Scan this QR with your phone: " + qr);
//                            try {
//                                Thread.sleep(10000);
//                            } catch (InterruptedException e) {
//                                e.printStackTrace();
//                            }
//                        })


                        //.qrHandler(QrHandler.toString(s -> System.out.println("QR CODE: " + s)))

//                //! Con Este da el PATH del QR CODE
//                .qrHandler(QrHandler.toFile(path -> {
//                    System.out.println("QR CODE2: " + path);
//                }))

//                //! Este crea el QR Code en esta ubicacion:
//                .qrHandler(
//                        QrHandler.toFile(Path.of("C:\\Users\\Joaquin\\Desktop\\qr.png"), path -> {
//                                    System.out.println("QR CODE2: " + path);
//                                }
//                        )
//                )

                        .build()
                        //.addLoggedInListener(() -> System.out.println("Connected!"))
                        .addListener(new MyListener())
                        .connect()
                        .join();


        System.out.println("FIN WspConfig.wsp()");

        return wsp;
    }


    public class MyListener implements Listener {

        @Override
        public void onLoggedIn(Whatsapp w) {
            System.out.println("-> Logged in!");
            //System.out.println(w.store().toJson());
        }

        @Override
        public void onContacts(Whatsapp whatsapp, Collection<Contact> contacts) {
            System.out.printf("Contacts: %s%n", contacts.size());
        }

        @Override
        public void onNewMessage(Whatsapp w, MessageInfo info) {
            System.out.println("INICIO MENSAJE RECIBIDO");

            if (!(info.message().content() instanceof TextMessage textMessage)) {
                return;
            }

            System.out.println("1 :" + info.senderJid().user()); //1 :5493515925801
            System.out.println("2 :" + info.senderName()); //2 :.
            System.out.println("3 :" + info.chatJid().user()); //3 :5493515925801
            System.out.println("4 :" + info.chatJid().toPhoneNumber()); //4 :+5493515925801
            info.sender().ifPresent(contact -> System.out.println("5: " + contact.chosenName() + " " + contact.name() + " " + contact.jid())); //5: . . 5493515925801@s.whatsapp.net
            System.out.println("6: " + textMessage.text()); // 6: Hola!!
            System.out.println("7: " + info.chat().jid());


//        System.out.println("---");
//        System.out.println(info.toJson());
//        System.out.println("---");


            System.out.println("FIN MENSAJE RECIBIDO");

        }

        @Override
        public void onStatus(Whatsapp whatsapp, Collection<MessageInfo> status) {

        }


        @Override
        public void onSocketEvent(Whatsapp whatsapp, SocketEvent event) {

        }

        @Override
        public void onNodeReceived(Whatsapp whatsapp, Node incoming) {

        }

        @Override
        public void onNodeSent(Whatsapp whatsapp, Node incoming) {
        }


    }


}
`

Use it in a controller:

`
import it.auties.whatsapp.api.Whatsapp;
import it.auties.whatsapp.model.contact.ContactJid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import java.util.NoSuchElementException;



@RestController
@RequestMapping("/api")
public class WspController {

    @Autowired
    private Whatsapp whatsappApi;

    @RequestMapping("/enviar")
    public ResponseEntity<?> test() {


        //ENVIAR MENSAJE
        // 1º Obtengo el chat
        var chat = whatsappApi.store()
                //.findChatByJid(ContactJid.of("xxxx@s.whatsapp.net"))
                .findChatByJid(ContactJid.of("xxxx@g.us"))
                //.findChatByName("My Awesome Friend")
                .orElseThrow(() -> new NoSuchElementException("Hey, you don't exist"));

        // 2º Envio el mensaje(deacuerdo al tipo)
        //1
        whatsappApi.sendMessage(chat, "Prueba Envio");

        return ResponseEntity.ok("Mensaje Enviado");
    }

    @GetMapping("/test2")
    public ResponseEntity<?> test2() {
        return ResponseEntity.ok("Hola Mundo");
    }

}
`



Tell us if you could make it work!

**Comment by Auties00** [comment]
In 3.4.5, I switched to jackson 2.15.0, so the issue with spring should be fixed

**Comment by koalsky** [comment]
@Auties00 @jandreotti Thank you for your code and help
