### ISSUE TITLE
MobileBuilder error

### ISSUE THREAD

**Issue by GomesDev0001** [Auties00/Cobalt#332]
![image](https://github.com/Auties00/Cobalt/assets/113743540/41a8f82e-7420-42c5-b57f-4bbd7275469c)
![image](https://github.com/Auties00/Cobalt/assets/113743540/8708225e-95bd-4da3-b32a-bd2c44f6bb53)

Hello, I'm having difficulties with this part, a while ago I opened a ticket talking about the same problem and you said it was rate limit, I'm on the first attempt and again the same error came back...

**Comment by GomesDev0001** [comment]
Exception in thread "main" java.util.concurrent.CompletionException: it.auties.whatsapp.exception.RegistrationException: VerificationCodeResponse[number=5513997947564, lid=0, status=ERROR, errorReason=NO_ROUTES, method=null, codeLength=0, notifyAfter=0, retryAfter=3600, voiceLength=0, voiceWait=3600, smsWait=3600, whatsappOtpWait=0, flashType=0, oldWait=0, securityCodeSet=false, whatsappOtpEligible=false]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: it.auties.whatsapp.exception.RegistrationException: VerificationCodeResponse[number=5513997947564, lid=0, status=ERROR, errorReason=NO_ROUTES, method=null, codeLength=0, notifyAfter=0, retryAfter=3600, voiceLength=0, voiceWait=3600, smsWait=3600, whatsappOtpWait=0, flashType=0, oldWait=0, securityCodeSet=false, whatsappOtpEligible=false]

**Comment by Auties00** [comment]
it's a rate limit, it's number based. Try another number

**Comment by GomesDev0001** [comment]
am I doing it right? (Number: (DD) (State) (Number)

**Comment by sailer132** [comment]
> it's a rate limit, it's number based. Try another number

I also encountered the same problem. When I applied for a verification code from WhatsApp, it return 'no_routes'
