### ISSUE TITLE
Custom serializer doesn't work with MobileOptionsBuilder

### ISSUE THREAD

**Issue by hamarna** [Auties00/Cobalt#358]
3.5.1

```
java.lang.NullPointerException: Cannot invoke "it.auties.whatsapp.controller.ControllerSerializer.linkMetadata(it.auties.whatsapp.controller.Controller)" because "this.serializer" is null
	at it.auties.whatsapp.controller.Controller.phoneNumber(Controller.java:105)
	at it.auties.whatsapp.api.MobileRegistrationBuilder$Unregistered.register(MobileRegistrationBuilder.java:125)
```

It works properly with web version. Also mobile version works if serializer is not set.

**Comment by Auties00** [comment]
Fixed on the master branch
