### ISSUE TITLE
Socket failure at CRYPTOGRAPHY

### ISSUE THREAD

**Issue by laotong95** [Auties00/Cobalt#426]
Dec 25, 2023 10:45:49 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac, last node: Node[description=message, attributes={type=text, participant=855716175059:2@s.whatsapp.net, notify=jaoan, participant_lid=230713228062876_1@s.whatsapp.net, addressing_mode=pn, t=1703475948, from=120363184975901227@g.us, id=B4A57EEBF1009DB76E}, content=[Node[description=enc, attributes={v=2, type=skmsg}, content=[51, 8, -22, -76, -106, -77, 6, 16, 21, 26, -96, 1, 96, 1, -24, -79, 34, 50, -83, 24, 50, 5, -120, -124, 26, 38, 71, -125, 67, 11, 30, -82, -75, 17, 122, -27, -5, 11, 52, -64, -103, -44, 81, 40, 31, -89, -113, -109, 70, 14, 66, 76, -85, 59, -29, -112, 125, 19, 92, -72, 10, 47, -84, 109, -81, 23, 33, 37, -122, -41, -125, -108, 27, -91, -54, 25, 124, 111, -64, 54, 47, -108, 110, -74, 41, 69, 32, -36, -24, 79, 33, 73, 35, -95, -71, -46, 57, 105, 17, -50, -11, 123, -20, 68, 126, -66, -95, 27, -125, 115, -60, -83, -59, 120, -123, -125, -58, 109, -30, 105, 29, -89, -123, 72, 18, 107, -67, -109, 19, -123, 45, 77, 62, -38, 69, -59, 15, 119, 0, -92, -91, 65, -119, -106, 21, 73, -116, 7, -103, -74, 110, -68, -66, -68, -66, 94, 36, 79, 20, -69, 15, -109, -38, -102, 105, 4, -4, 70, -65, -11, 11, 56, -128, 6, -12, 15, 83, 58, -6, -66, -78, -41, -70, -19, -104, -84, -60, -126, -108, -40, 18, 102, -85, 3, -101, 77, 21, 51, 115, 72, 50, -86, 53, 96, -76, -47, -47, 6, 69, -81, -94, 24, 48, -83, 64, 10, 91, 49, 16, -8, -43, -24, -7, -125, -110, 38, 104, 51, -58, 32, -46, -52, 92, 78, 52, -116]]]]
	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:614)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:103)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:206)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:123)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Dec 25, 2023 10:45:49 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Socket failure at CRYPTOGRAPHY

**Comment by laotong95** [comment]
This problem occurs after running the program for a while. Can anyone tell me how to solve it?

**Comment by Auties00** [comment]
Tracked in https://github.com/Auties00/Cobalt/issues/292

**Comment by imJohnYeager** [comment]
> This problem occurs after running the program for a while. Can anyone tell me how to solve it?

Have you managed to resolve it yet? I'm in the same situation.
