### ISSUE TITLE
Unknown privacy value: known

### ISSUE THREAD

**Issue by LautjeDS** [Auties00/Cobalt#442]
When logging in I get the following error:

> java.util.concurrent.CompletionException: java.util.NoSuchElementException: Unknown privacy value: known
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.NoSuchElementException: Unknown privacy value: known
	at it.auties.whatsapp.socket.StreamHandler.lambda$addPrivacySetting$47(StreamHandler.java:746)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.whatsapp.socket.StreamHandler.addPrivacySetting(StreamHandler.java:746)
	at it.auties.whatsapp.socket.StreamHandler.lambda$parsePrivacySettings$91(StreamHandler.java:1156)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at it.auties.whatsapp.socket.StreamHandler.parsePrivacySettings(StreamHandler.java:1157)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 6 more

I am using the Web API and it does log in because I can see the device getting added on my phone.

**Comment by Auties00** [comment]
> When logging in I get the following error:
> 
> > java.util.concurrent.CompletionException: java.util.NoSuchElementException: Unknown privacy value: known
> > at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> > at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> > at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
> > at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
> > at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
> > at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
> > at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
> > at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
> > at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
> > Caused by: java.util.NoSuchElementException: Unknown privacy value: known
> > at it.auties.whatsapp.socket.StreamHandler.lambda$addPrivacySetting$47(StreamHandler.java:746)
> > at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> > at it.auties.whatsapp.socket.StreamHandler.addPrivacySetting(StreamHandler.java:746)
> > at it.auties.whatsapp.socket.StreamHandler.lambda$parsePrivacySettings$91(StreamHandler.java:1156)
> > at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> > at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
> > at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> > at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> > at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> > at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> > at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> > at it.auties.whatsapp.socket.StreamHandler.parsePrivacySettings(StreamHandler.java:1157)
> > at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
> > ... 6 more
> 
> I am using the Web API and it does log in because I can see the device getting added on my phone.

It could be a new feature from Whatsapp, do you have any new values in the privacy section of the app?

**Comment by codespearhead** [comment]
Check whether the problem persists when you use the standard version of WhatsApp.

As the name suggests, using the beta version might be unreliable since it's a rolling release instead of a stable release.

**Comment by Auties00** [comment]
Fixed in 0.0.5
