### ISSUE TITLE
Image sending failed with cobalt 0.0.2 , plz guide me. 

### ISSUE THREAD

**Issue by BodduSatya** [Auties00/Cobalt#450]
try {
	var mobileNumber ="xxxxxxxxxxx";
	var chat = whatsappApi.store()
			.findChatByJid(ContactJid.of(msg.getToMobileNumber()))
			.orElseThrow(() -> new NoSuchElementException("Hey,"+mobileNumber+" not exist"));

			var media = Files.readAllBytes(Path.of("C:\\Users\\xxxxxxxxxxx\\OneDrive\\Pictures\\1971961.jpg"));

			var image = new ImageMessageSimpleBuilder() // Create a new image message builder
                            .media(media) // Set the image of this message
                            .mimeType(String.valueOf(MediaMessageType.IMAGE))
                            .caption("some awesome caption") // Set the caption of this message
                            .thumbnail(media)
                            .contextInfo(contextInfo)
                            .build(); // Create the message
                    whatsappApi.sendMessage(chat,  image);

}catch(Exception e){
e.printStacktrace();
}

**Exception stacktrace**
java.lang.NoSuchMethodError: 'it.auties.whatsapp.model.message.standard.ImageMessage it.auties.whatsapp.model.message.standard.ImageMessage.simpleBuilder(byte[], java.lang.String, java.lang.String, byte[], it.auties.whatsapp.model.info.ContextInfo)'
	at it.auties.whatsapp.model.message.standard.ImageMessageSimpleBuilder.build(ImageMessageSimpleBuilder.java:35) ~[cobalt-0.0.2.jar:na]
	at org.satya.whatsapp.controller.WspController.test(WspController.java:58) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:261) ~[spring-web-6.1.3.jar:6.1.3]

**Comment by Auties00** [comment]
should be fixed in 0.0.3
