### ISSUE TITLE
Disconnected: LOGGED_OUT on cobalt 0.0.4

### ISSUE THREAD

**Issue by nfrfab** [Auties00/Cobalt#469]
The app works fine for hours and suddenly a severe exception occurs

Disconnected: RECONNECTING
Connected: [PrivacySettingEntry[type=READ_RECEIPTS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=STATUS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=PROFILE_PIC, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ONLINE, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=CALL_ADD, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ADD_ME_TO_GROUPS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=LAST_SEEN, value=EVERYONE, excluded=[]]]
Disconnected: RECONNECTING
abr 02, 2024 1:57:37 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac. Unresolved nodes: Node[description=iq, attributes={xmlns=w:m, to=s.whatsapp.net, type=set, id=1711662641-346}, content=[Node[description=media_conn]]]
Node[description=iq, attributes={xmlns=w:p, to=s.whatsapp.net, type=get, id=1711662641-345}, content=[Node[description=ping]]]
	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:840)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:102)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:193)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.notifyMessage(SocketSession.java:150)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:139)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processBinary(WebSocketImpl.java:618)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:447)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:282)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:251)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.tryChangeState(WebSocketImpl.java:861)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$SignallingMessageConsumer.onBinary(WebSocketImpl.java:802)
	at java.net.http/jdk.internal.net.http.websocket.MessageDecoder.payloadData(MessageDecoder.java:223)
	at java.net.http/jdk.internal.net.http.websocket.Frame$Reader.readFrame(Frame.java:473)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:675)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReadEvent.handle(TransportImpl.java:772)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.checkEvents(RawChannelTube.java:174)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:204)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:157)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:451)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:269)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.lang.Thread.run(Thread.java:1583)
abr 02, 2024 1:57:37 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Restore
Connected: [PrivacySettingEntry[type=READ_RECEIPTS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=STATUS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=PROFILE_PIC, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ONLINE, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=CALL_ADD, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ADD_ME_TO_GROUPS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=LAST_SEEN, value=EVERYONE, excluded=[]]]
Disconnected: RESTORE
Disconnected: LOGGED_OUT

**Comment by Auties00** [comment]
I've fixed this, i'll push by next week the fix

**Comment by Auties00** [comment]
Btw being tracked in https://github.com/Auties00/Cobalt/issues/292
