### ISSUE TITLE
Socket failure at MEDIA_CONNECTION - Cobalt 0.0.4

### ISSUE THREAD

**Issue by nfrfab** [Auties00/Cobalt#471]
The exception occurs randomly

abr 03, 2024 10:59:20 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.TimeoutException
	... 7 more
abr 03, 2024 10:59:20 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Ignored failure

**Comment by nfrfab** [comment]
When that type of error appears, it repeats every 5 minutes

abr 05, 2024 9:13:49 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.TimeoutException
        ... 7 more
abr 05, 2024 9:13:49 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Ignored failure
abr 05, 2024 9:18:49 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.TimeoutException
        ... 7 more
abr 05, 2024 9:18:49 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Ignored failure
abr 05, 2024 9:23:49 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.TimeoutException
        ... 7 more
abr 05, 2024 9:23:49 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Ignored failure
abr 05, 2024 9:28:49 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.TimeoutException
        ... 7 more
abr 05, 2024 9:28:49 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Ignored failure

...

**Comment by Auties00** [comment]
Try with cobalt 0.0.5 and let me know if the issue is still there

**Comment by Darker935** [comment]
It's fixed @nfrfab ? Or not
