### ISSUE TITLE
Error Compile SocketHandler.class

### ISSUE THREAD

**Issue by KanzakiisYU** [Auties00/Cobalt#479]
Android Studio: Hedgehog 2023 Patch 1 | AGP VERSION: 8.2.1 | GRADLE VERSION: 8.5 | JDK VER: OPENJDK 21

> build.gradle
```
plugins {
    id 'com.android.application'
}



android {
    namespace 'com.konjousoft.whatsappbot'
    compileSdk 34

    defaultConfig {
        applicationId "com.konjousoft.whatsappbot"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}




dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.github.auties00:cobalt:0.0.5'
    implementation "androidx.multidex:multidex:2.0.1"
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    annotationProcessor 'com.github.auties00:cobalt:0.0.5'

}
```

> THE ERROR:
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform cobalt-0.0.5.jar (com.github.auties00:cobalt:0.0.5) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\DELL\.gradle\caches\modules-2\files-2.1\com.github.auties00\cobalt\0.0.5\16a6cf161abf964278c3aad155c35c73c71af435\cobalt-0.0.5.jar.
         > Error while dexing.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeExtDexDebug'.
	
Caused by: org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform cobalt-0.0.5.jar (com.github.auties00:cobalt:0.0.5) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
	at org.gradle.api.internal.artifacts.transform.TransformingAsyncArtifactListener$TransformedArtifact.lambda$visit$4(TransformingAsyncArtifactListener.java:243)
Caused by: org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform cobalt-0.0.5.jar (com.github.auties00:cobalt:0.0.5) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

Caused by: org.gradle.api.internal.artifacts.transform.TransformException: Execution failed for DexingNoClasspathTransform: C:\Users\DELL\.gradle\caches\modules-2\files-2.1\com.github.auties00\cobalt\0.0.5\16a6cf161abf964278c3aad155c35c73c71af435\cobalt-0.0.5.jar.
	at org.gradle.api.internal.artifacts.transform.DefaultTransformInvocationFactory.lambda$createInvocation$1(DefaultTransformInvocationFactory.java:116)
	Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\DELL\.gradle\caches\modules-2\files-2.1\com.github.auties00\cobalt\0.0.5\16a6cf161abf964278c3aad155c35c73c71af435\cobalt-0.0.5.jar:it/auties/whatsapp/socket/SocketHandler.class
	at Version.fakeStackEntry(Version_8.2.42.java:0)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\DELL\.gradle\caches\modules-2\files-2.1\com.github.auties00\cobalt\0.0.5\16a6cf161abf964278c3aad155c35c73c71af435\cobalt-0.0.5.jar:it/auties/whatsapp/socket/SocketHandler.class
```

**Comment by Auties00** [comment]
Sorry android is not supported right now
