### ISSUE TITLE
Error: Cannot decrypt data

### ISSUE THREAD

**Issue by SixPathsLT** [Auties00/Cobalt#514]
This will randomly occur and start spamming the console and the only way to fix it, is by restarting the entire application. Is there a way to completely close the instance of Whatsapp? 

`Whatsapp apiInstance = Whatsapp.webBuilder().newConnection(id);`

```
SEVERE: [971501502233] Socket failure at UNKNOWN
java.lang.RuntimeException: Cannot decrypt data
        at it.auties.whatsapp.crypto.AesGcm.cipher(AesGcm.java:29)
        at it.auties.whatsapp.crypto.AesGcm.decrypt(AesGcm.java:74)
        at it.auties.whatsapp.crypto.AesGcm.decrypt(AesGcm.java:66)
        at it.auties.whatsapp.implementation.SocketHandler.onMessage(SocketHandler.java:194)
        at it.auties.whatsapp.implementation.SocketSession$WebSocketSession.onMessage(SocketSession.java:119)
        at it.auties.whatsapp.net.WebSocketClient$MessageDecoder.payloadData(WebSocketClient.java:442)
        at it.auties.whatsapp.net.WebSocketClient$MessageDecoder.handlePayloadData(WebSocketClient.java:282)
        at it.auties.whatsapp.net.WebSocketClient$MessageDecoder.handleFrame(WebSocketClient.java:268)
        at it.auties.whatsapp.net.WebSocketClient$MessageDecoder.readFrame(WebSocketClient.java:255)
        at it.auties.whatsapp.net.WebSocketClient.lambda$listen$1(WebSocketClient.java:93)
        at it.auties.whatsapp.net.Response.complete(Response.java:8)
        at it.auties.whatsapp.net.SocketClient$SocketTransport$Secure.decodeSslBuffer(SocketClient.java:843)
        at it.auties.whatsapp.net.SocketClient$SocketTransport$Secure.lambda$fillSslBuffer$2(SocketClient.java:829)
        at it.auties.whatsapp.net.Response.complete(Response.java:8)
        at it.auties.whatsapp.net.SocketClient$SocketTransport$1.completed(SocketClient.java:563)
        at it.auties.whatsapp.net.SocketClient$SocketTransport$1.completed(SocketClient.java:549)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:284)
        at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(WindowsAsynchronousSocketChannelImpl.java:586)
        at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:387)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch
        at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1545)
        at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:443)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2190)
        at it.auties.whatsapp.crypto.AesGcm.cipher(AesGcm.java:26)
        ... 23 more
Sep 05, 2024 4:50:33 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: [971501502233] Ignored failure
Sep 05, 2024 4:50:34 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: [971501502233] Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@60ac5bff[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@764a213a[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@71ec21d4]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3b166026[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@60ac5bff[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@764a213a[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@71ec21d4]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3b166026[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at it.auties.whatsapp.implementation.SocketHandler.scheduleDelayed(SocketHandler.java:1157)
        at it.auties.whatsapp.implementation.StreamHandler.onMediaConnection(StreamHandler.java:1399)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        ... 6 more
Sep 05, 2024 4:50:34 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: [971501502233] Ignored failure
API Error: OPEN- OPEN
Disconnected: RECONNECTING
API Error: OPEN- OPEN
Sep 05, 2024 4:50:35 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: [971501502233] Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6f3e5e46[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@3d8a5473[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@588e2841]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d8edb9a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6f3e5e46[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@3d8a5473[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@588e2841]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d8edb9a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at it.auties.whatsapp.implementation.SocketHandler.scheduleDelayed(SocketHandler.java:1157)
        at it.auties.whatsapp.implementation.StreamHandler.onMediaConnection(StreamHandler.java:1399)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        ... 6 more
Sep 05, 2024 4:50:35 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: [971501502233] Ignored failure
Sep 05, 2024 4:50:35 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: [971501502233] Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1bc404e1[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7a0a1d21[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@4eb422b1]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3b166026[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1bc404e1[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7a0a1d21[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@4eb422b1]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3b166026[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at it.auties.whatsapp.implementation.SocketHandler.scheduleDelayed(SocketHandler.java:1157)
        at it.auties.whatsapp.implementation.StreamHandler.onMediaConnection(StreamHandler.java:1399)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        ... 6 more
Sep 05, 2024 4:50:35 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: [971501502233] Ignored failure
Disconnected: RECONNECTING
API Error: OPEN- OPEN
Disconnected: RECONNECTING
Sep 05, 2024 4:50:36 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: [971501502233] Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@29a9bc8a[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@77c5572f[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@75b4898b]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d8edb9a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@29a9bc8a[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@77c5572f[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@75b4898b]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d8edb9a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at it.auties.whatsapp.implementation.SocketHandler.scheduleDelayed(SocketHandler.java:1157)
        at it.auties.whatsapp.implementation.StreamHandler.onMediaConnection(StreamHandler.java:1399)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        ... 6 more
Sep 05, 2024 4:50:36 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: [971501502233] Ignored failure
API Error: OPEN- OPEN
Disconnected: RECONNECTING
Sep 05, 2024 4:50:36 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: [971501502233] Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@48e583c7[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7b0c6385[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@1fa5cd82]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3b166026[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@48e583c7[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7b0c6385[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@1fa5cd82]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3b166026[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at it.auties.whatsapp.implementation.SocketHandler.scheduleDelayed(SocketHandler.java:1157)
        at it.auties.whatsapp.implementation.StreamHandler.onMediaConnection(StreamHandler.java:1399)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        ... 6 more
Sep 05, 2024 4:50:36 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: [971501502233] Ignored failure
API Error: OPEN- OPEN
Disconnected: RECONNECTING
Sep 05, 2024 4:50:37 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: [971501502233] Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@48db127[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@245002f1[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@6bcf7b3e]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d8edb9a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@48db127[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@245002f1[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@6bcf7b3e]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d8edb9a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at it.auties.whatsapp.implementation.SocketHandler.scheduleDelayed(SocketHandler.java:1157)
        at it.auties.whatsapp.implementation.StreamHandler.onMediaConnection(StreamHandler.java:1399)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        ... 6 more
Sep 05, 2024 4:50:37 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: [971501502233] Ignored failure
API Error: OPEN- OPEN
Disconnected: RECONNECTING
Sep 05, 2024 4:50:38 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: [971501502233] Socket failure at MEDIA_CONNECTION
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3d83c0c1[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@386d3316[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@3808c004]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3b166026[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3d83c0c1[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@386d3316[Wrapped task = it.auties.whatsapp.implementation.StreamHandler$$Lambda/0x000001d0303d3db8@3808c004]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3b166026[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at it.auties.whatsapp.implementation.SocketHandler.scheduleDelayed(SocketHandler.java:1157)
        at it.auties.whatsapp.implementation.StreamHandler.onMediaConnection(StreamHandler.java:1399)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        ... 6 more
Sep 05, 2024 4:50:38 P.M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: [971501502233] Ignored failure
API Error: OPEN- OPEN
```

**Comment by Auties00** [comment]
Try 0.0.7, also I need the code you used

**Comment by SixPathsLT** [comment]
Unable to build 0.0.7 due to the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project cobalt: Fatal error compiling: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project cobalt: Fatal error compiling
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1143)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:193)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 18 more
Caused by: org.codehaus.plexus.compiler.CompilerException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:198)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:183)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1140)
	... 21 more
Caused by: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:168)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:136)
	... 23 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at jdk.compiler/com.sun.tools.javac.util.List.get(List.java:476)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.getTypeParameter(ProtobufJavacPlugin.java:830)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.attributeSerializers(ProtobufJavacPlugin.java:688)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.attributeSerializers(ProtobufJavacPlugin.java:646)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.getConcreteCollectionType(ProtobufJavacPlugin.java:531)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.getPropertyType(ProtobufJavacPlugin.java:476)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.processMessageProperty(ProtobufJavacPlugin.java:353)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.handleField(ProtobufJavacPlugin.java:228)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.processMessage(ProtobufJavacPlugin.java:160)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.processMessage(ProtobufJavacPlugin.java:134)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.processElement(ProtobufJavacPlugin.java:126)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.processObjects(ProtobufJavacPlugin.java:88)
	at it.auties.protobuf.serialization.ProtobufJavacPlugin.process(ProtobufJavacPlugin.java:76)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1021)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:937)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1265)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1380)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1272)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	... 26 more
```

As for the WhatsApp instance, I'm using the code provided in the Web Example:
```
Whatsapp apiInstance =   Whatsapp.webBuilder()
                .newConnection(userId)
                .unregistered(QrHandler.toTerminal())
                .addLoggedInListener(api -> System.out.printf("Connected: %s%n", api.store().privacySettings()))
                .addDisconnectedListener(reason -> System.out.printf("Disconnected: %s%n", reason))
                .connect()
                .join()
```
