### ISSUE TITLE
cobalt-0.0.7 Image & Document sending not working, using web pairing method

### ISSUE THREAD

**Issue by BodduSatya** [Auties00/Cobalt#515]
cobalt-0.0.7 Image & Document sending not working, using web pairing method

java.lang.IllegalStateException: Unsupported mobile osjava.util.concurrent.CompletionException: java.lang.IllegalStateException: Unsupported mobile os
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.IllegalStateException: Unsupported mobile os
	at it.auties.whatsapp.model.companion.CompanionDevice.platformName(CompanionDevice.java:180)
	at it.auties.whatsapp.model.companion.CompanionDevice.toUserAgent(CompanionDevice.java:127)
	at it.auties.whatsapp.implementation.MessageHandler.attributeMediaMessage(MessageHandler.java:235)
	at it.auties.whatsapp.implementation.MessageHandler.prepareOutgoingChatMessage(MessageHandler.java:139)
	at it.auties.whatsapp.implementation.MessageHandler.encodeChatMessage(MessageHandler.java:109)
	at it.auties.whatsapp.implementation.MessageHandler.encode(MessageHandler.java:103)
	at it.auties.whatsapp.implementation.SocketHandler.sendMessage(SocketHandler.java:487)
	at it.auties.whatsapp.api.Whatsapp.lambda$sendMessage$20(Whatsapp.java:820)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 6 more

2024-09-06 06:28:58 [ForkJoinPool.commonPool-worker-6] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:29:18 [ForkJoinPool.commonPool-worker-4] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:29:38 [ForkJoinPool.commonPool-worker-8] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:29:58 [ForkJoinPool.commonPool-worker-2] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:30:18 [ForkJoinPool.commonPool-worker-7] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:30:38 [ForkJoinPool.commonPool-worker-9] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:30:58 [ForkJoinPool.commonPool-worker-10] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:31:18 [ForkJoinPool.commonPool-worker-10] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:31:38 [ForkJoinPool.commonPool-worker-8] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file
2024-09-06 06:31:58 [ForkJoinPool.commonPool-worker-7] ERROR Serializer - java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot write file

**Comment by Pachuchi420** [comment]
Yeah after further testing, I found that I get the same error as Boddu: 

`java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unsupported mobile os
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.IllegalStateException: Unsupported mobile os
	at it.auties.cobalt@0.0.7/it.auties.whatsapp.model.companion.CompanionDevice.platformName(CompanionDevice.java:180)
	at it.auties.cobalt@0.0.7/it.auties.whatsapp.model.companion.CompanionDevice.toUserAgent(CompanionDevice.java:127)
	at it.auties.cobalt@0.0.7/it.auties.whatsapp.implementation.MessageHandler.attributeMediaMessage(MessageHandler.java:235)
	at it.auties.cobalt@0.0.7/it.auties.whatsapp.implementation.MessageHandler.prepareOutgoingChatMessage(MessageHandler.java:139)
	at it.auties.cobalt@0.0.7/it.auties.whatsapp.implementation.MessageHandler.encodeChatMessage(MessageHandler.java:109)
	at it.auties.cobalt@0.0.7/it.auties.whatsapp.implementation.MessageHandler.encode(MessageHandler.java:103)
	at it.auties.cobalt@0.0.7/it.auties.whatsapp.implementation.SocketHandler.sendMessage(SocketHandler.java:487)
	at it.auties.cobalt@0.0.7/it.auties.whatsapp.api.Whatsapp.lambda$sendMessage$20(Whatsapp.java:820)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 6 more`


There's some sort of lack of handling for the web client I suppose? I tried looking into it but honestly I'm clueless as to how to fix it. I guess there's something missing within CompanionDevice.java? I tried looking into it and found two methods that might need some sort of extra handling, especially the web case: 

- deviceName()
- platformName()

But again I'm not too sure. I tried to find a fix but without further understanding of the whole code base I can't do much. The code is really well put together tho, the java docs are great, but again I'm kind of new at this so it's out of my pay grade lol. 

Attached are my [project files.](https://github.com/user-attachments/files/16926043/whatsappTest.zip)

As well as a [quick nice video](https://imgur.com/a/VoNoWm5) demonstrating the error again:


![](https://i.imgur.com/KVvp0cT.gif)


Hopefully we can figure something out!

**Comment by Auties00** [comment]
will be fixed in 0.0.8

**Comment by piLovr** [comment]
Same error here, I was trying to send a StickerMessage

**Comment by pcvarma-sayukth** [comment]
I too get the same error with v0.0.7, WEB mode and trying to send Image and PDF files 

Caused by: java.lang.IllegalStateException: Unsupported mobile os
	at it.auties.whatsapp.model.companion.CompanionDevice.platformName(CompanionDevice.java:180)
	at it.auties.whatsapp.model.companion.CompanionDevice.toUserAgent(CompanionDevice.java:127)
	at it.auties.whatsapp.implementation.MessageHandler.attributeMediaMessage(MessageHandler.java:235)
	at it.auties.whatsapp.implementation.MessageHandler.prepareOutgoingChatMessage(MessageHandler.java:139)
	at it.auties.whatsapp.implementation.MessageHandler.encodeChatMessage(MessageHandler.java:109)
	at it.auties.whatsapp.implementation.MessageHandler.encode(MessageHandler.java:103)
	at it.auties.whatsapp.implementation.SocketHandler.sendMessage(SocketHandler.java:487)
	at it.auties.whatsapp.api.Whatsapp.lambda$sendMessage$20(Whatsapp.java:820)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1194)
	... 5 more

**Comment by ItsLaivy** [comment]
Any update here? There's no way to send image messages using 0.0.7 Cobalt then? :(

**Comment by Auties00** [comment]
> Any update here? There's no way to send image messages using 0.0.7 Cobalt then? :(

As I mentioned, i’m working on decoupling the network stack from cobalt into the Leap project. I'm almost done with it, then I'll release 0.0.8. Sorry for the wait

**Comment by pcvarma-sayukth** [comment]
@Auties00 
If possible, please let us know the tentative time line for 0.0.8 release based on your convenience.

**Comment by Auties00** [comment]
Fixed in 0.0.8!
