### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Pabloku** [Auties00/Cobalt#517]
Hi!

I'm trying to use this library in an Android project using Android Studio. I was able to compile it and I'm trying to execute this piece of code:

```
     Whatsapp.mobileBuilder().newConnection(600123123)
            .device(CompanionDevice.android(false))
            .registered()
            .get()
            .addNewChatMessageListener { first, second ->
                Log.d("Test", "Whatsapp msg received: ${second.message().content()}")
            }
            .connect()
```

But I get this error:

```
FATAL EXCEPTION: main
Process: com.example.whatsappreader, PID: 30185
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/annotation/processing/AbstractProcessor;
	at com.example.whatsappreader.MainActivity.onCreate(MainActivity.kt:35)
	at android.app.Activity.performCreate(Activity.java:9019)
	at android.app.Activity.performCreate(Activity.java:8997)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1528)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4021)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4226)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2635)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8700)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.annotation.processing.AbstractProcessor" on path: DexPathList[[zip file "/data/app/~~iAMEIiCj6gyg7E5WYKLbnw==/com.example.whatsappreader-6lMb0Q2svoIUoatdpTzZcg==/base.
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	... 18 more
```

Could you give me a hand?

Thanks very much!

**Comment by Auties00** [comment]
Android is not supported and I don't have an android device on hand so I can't help you
But if you fix it let me know
Also keep in mind that i forgot to push some files in 0.0.7 so you can't compile from source directly
Will be fixed in 0.0.8, eta next week

**Comment by legendsayantan** [comment]
Same issue in hand, would be nice if there were plans to add android support.

**Comment by Auties00** [comment]
I dropped annotation support in 0.0.10, so maybe now it works

**Comment by legendsayantan** [comment]
is 0.0.10 released yet? cause it looks like right now gradle can only resolve up to 0.0.9

**Comment by Onako2** [comment]
> is 0.0.10 released yet? cause it looks like right now gradle can only resolve up to 0.0.9

0.0.10 works (at least when trying yesterday)

Is the issue still occuring?

**Comment by Auties00** [comment]
this will likely never be possible after the refactor because of the native dependencies(audio/video codecs) for calls:
I'll leave it open in case someone wants to work on it
