### ISSUE TITLE
Most TextMessages not working

### ISSUE THREAD

**Issue by piLovr** [Auties00/Cobalt#525]
I got problems with reaction, textmessage w/ quotedMessage and Complex Text, See below:
(Using web login)

Reaction:
`api.sendReaction(messageInfo, Emoji.EGGPLANT).join();`

> The message "sends", I  get a MessageInfo Object back, this looks normal, but no message is to be seen, also no *Waiting for this Message* stuff. deliveredJids is existing...

Quoted Message:
```
var c = new ContextInfoBuilder()
        .quotedMessage(m.messageContainer)
        .build();
var message2 = new TextMessageBuilder()
        .contextInfo(c)
        .text("Test")
        .build();
whatsapp.sendMessage(Jid, message2).join();        
```

>Nothing, just like reactionMessage

Complex Test: (Basically the example)
```
var message = new TextMessageBuilder() // Create a new text message
        .text("Check this video out: https://www.youtube.com/watch?v=dQw4w9WgXcQ") // Set the text of the message
        .canonicalUrl("https://www.youtube.com/watch?v=dQw4w9WgXcQ") // Set the url of the message
        .matchedText("https://www.youtube.com/watch?v=dQw4w9WgXcQ") // Set the matched text for the url in the message
        .title("A nice suprise") // Set the title of the url
        .description("Check me out") // Set the description of the url
        .build(); // Create the message
whatsapp.sendMessage(jid,  message);

```

> Okt. 08, 2024 10:46:51 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SCHWERWIEGEND: [_myNumber_] Socket failure at MESSAGE
java.util.concurrent.CompletionException: it.auties.whatsapp.exception.RequestException: Node timed out: Node[description=message, attributes={id=3EB0A6BF68D4218D329FB5, to=_myGroup_@g.us, type=text}, content=[Node[description=enc, attributes={v=2, type=skmsg}, content=[
    *a hella large amount of data*
]]]]
	at it.auties.whatsapp.implementation.SocketRequest.futureOrTimeout(SocketRequest.java:24)
	at it.auties.whatsapp.implementation.SocketRequest.<init>(SocketRequest.java:20)
	at it.auties.whatsapp.implementation.SocketRequest.of(SocketRequest.java:34)
	at it.auties.whatsapp.implementation.SocketHandler.sendNode(SocketHandler.java:270)
	at it.auties.whatsapp.implementation.SocketHandler.sendNode(SocketHandler.java:262)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
	Suppressed: java.util.concurrent.TimeoutException
		at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1570)
Okt. 08, 2024 10:46:51 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNUNG: [_myNumber_] Ignored failure

**Comment by Auties00** [comment]
Linked to a prior issue, already fixed, will be pushed soon
