### ISSUE TITLE
Jid parsing ploblem

### ISSUE THREAD

**Issue by aleksandrchechenev** [Auties00/Cobalt#527]
I faced a problem when connecting my account for the first time. During history synchronization, this error occurred. I think it is caused by an unknown JidServer name. Looks like a bug

java.lang.NumberFormatException: For input string: "99@hosted"
 at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
 at java.base/java.lang.Integer.parseInt(Integer.java:662)
 at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:840)
 at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:934)
 at it.auties.whatsapp.model.jid.Jid.of(Jid.java:57)
 at it.auties.whatsapp.model.jid.Jid.of(Jid.java:118)
 at it.auties.whatsapp.model.jid.Jid.ofProtobuf(Jid.java:38)
 at it.auties.whatsapp.model.message.model.MessageReceiptSpec.decode(MessageReceiptSpec.java:79)
 at it.auties.whatsapp.model.info.ChatMessageInfoSpec.decode(ChatMessageInfoSpec.java:277)
 at it.auties.whatsapp.model.sync.HistorySyncMessageSpec.decode(HistorySyncMessageSpec.java:32)
 at it.auties.whatsapp.model.chat.ChatSpec.decode(ChatSpec.java:140)
 at it.auties.whatsapp.model.sync.HistorySyncSpec.decode(HistorySyncSpec.java:73)
 at it.auties.whatsapp.model.sync.HistorySyncSpec.decode(HistorySyncSpec.java:54)
 at it.auties.whatsapp.implementation.MessageHandler.lambda$downloadHistorySyncNotification$81(MessageHandler.java:1232)
 at java.base/java.util.Optional.map(Optional.java:260)
 at it.auties.whatsapp.implementation.MessageHandler.downloadHistorySyncNotification(MessageHandler.java:1232)
 at java.base/java.util.Optional.map(Optional.java:260)
 at it.auties.whatsapp.implementation.MessageHandler.downloadHistorySync(MessageHandler.java:1226)
 at it.auties.whatsapp.implementation.MessageHandler.onHistorySyncNotification(MessageHandler.java:1209)
 at it.auties.whatsapp.implementation.MessageHandler.handleProtocolMessage(MessageHandler.java:1160)
 at it.auties.whatsapp.implementation.MessageHandler.saveMessage(MessageHandler.java:1124)
 at it.auties.whatsapp.implementation.MessageHandler.decodeChatMessage(MessageHandler.java:999)
 at it.auties.whatsapp.implementation.MessageHandler.lambda$decode$56(MessageHandler.java:750)
 at java.base/java.lang.Iterable.forEach(Iterable.java:75)
 at it.auties.whatsapp.implementation.MessageHandler.decode(MessageHandler.java:750)
 at it.auties.whatsapp.implementation.SocketHandler.decodeMessage(SocketHandler.java:459)
 at it.auties.whatsapp.implementation.StreamHandler.digest(StreamHandler.java:115)
 at it.auties.whatsapp.implementation.SocketHandler.onMessage(SocketHandler.java:205)
 at it.auties.whatsapp.implementation.SocketSession$WebSocketSession.onMessage(SocketSession.java:119)
 at it.auties.whatsapp.net.WebSocketClient$MessageDecoder.payloadData(WebSocketClient.java:442)
 at it.auties.whatsapp.net.WebSocketClient$MessageDecoder.handlePayloadData(WebSocketClient.java:282)
 at it.auties.whatsapp.net.WebSocketClient$MessageDecoder.handleFrame(WebSocketClient.java:268)
 at it.auties.whatsapp.net.WebSocketClient$MessageDecoder.readFrame(WebSocketClient.java:255)
 at it.auties.whatsapp.net.WebSocketClient.lambda$listen$1(WebSocketClient.java:93)
 at it.auties.whatsapp.net.Response.complete(Response.java:8)
 at it.auties.whatsapp.net.SocketClient$SocketTransport$Secure.decodeSslBuffer(SocketClient.java:846)
 at it.auties.whatsapp.net.SocketClient$SocketTransport$Secure.lambda$fillSslBuffer$2(SocketClient.java:832)
 at it.auties.whatsapp.net.Response.complete(Response.java:8)
 at it.auties.whatsapp.net.SocketClient$SocketTransport$1.completed(SocketClient.java:566)
 at it.auties.whatsapp.net.SocketClient$SocketTransport$1.completed(SocketClient.java:552)
 at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
 at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:160)
 at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:573)
 at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
 at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
 at java.base/java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425)
 at it.auties.whatsapp.net.SocketClient$SocketTransport.readPlain(SocketClient.java:552)

**Comment by Auties00** [comment]
Fixed, thanks for showing me
