### ISSUE TITLE
Compilation Error while compiling Master or v0.0.7(Commit 73d4d61)

### ISSUE THREAD

**Issue by pcvarma-sayukth** [Auties00/Cobalt#530]
Hi [Auties00](Alessandro Autiero)
I sincerely appreciate your effort in the developing this project, it is very much helpful to send Whatsapp messages programmatically.

I am new to this domain, and tried to develop a pecie of code to connect  mode:WEB send the simple Text, Complex text, Image, Location and PDF files.
Unfortunately, i failed to send Complex text, Image and PDF files.
I got the following error,
Caused by: java.lang.IllegalStateException: Unsupported mobile os
	at it.auties.whatsapp.model.companion.CompanionDevice.platformName(CompanionDevice.java:180)
	at it.auties.whatsapp.model.companion.CompanionDevice.toUserAgent(CompanionDevice.java:127)
	at it.auties.whatsapp.implementation.MessageHandler.attributeMediaMessage(MessageHandler.java:235)
	at it.auties.whatsapp.implementation.MessageHandler.prepareOutgoingChatMessage(MessageHandler.java:139)
	at it.auties.whatsapp.implementation.MessageHandler.encodeChatMessage(MessageHandler.java:109)
	at it.auties.whatsapp.implementation.MessageHandler.encode(MessageHandler.java:103)
	at it.auties.whatsapp.implementation.SocketHandler.sendMessage(SocketHandler.java:487)
	at it.auties.whatsapp.api.Whatsapp.lambda$sendMessage$20(Whatsapp.java:820)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1194)
	... 5 more

I want to help and fix a few issues, then i checkout the latest code from master brach and tried to compile with the following environment
Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)
Maven home: /opt/apache-maven-3.9.3
Java version: 23.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-23.0.1.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "15.0.1", arch: "x86_64", family: "mac"

I used the following maven command to compile the code
mvn clean package -DskipTests -Dmaven.test.skip=true -e -X

I got the following compilation error, looks like there is an issue with either ProtoBuffer files or ProtoBuffer-Javac-Compiler logic.
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at com.sun.tools.javac.util.List.get (List.java:476)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.getTypeParameter (ProtobufJavacPlugin.java:983)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.attributeSerializers (ProtobufJavacPlugin.java:841)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.attributeSerializers (ProtobufJavacPlugin.java:799)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.getConcreteCollectionType (ProtobufJavacPlugin.java:684)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.getPropertyType (ProtobufJavacPlugin.java:619)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.processMessageProperty (ProtobufJavacPlugin.java:491)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.handleField (ProtobufJavacPlugin.java:361)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.processMessage (ProtobufJavacPlugin.java:181)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.processMessage (ProtobufJavacPlugin.java:146)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.processElement (ProtobufJavacPlugin.java:138)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.processObjects (ProtobufJavacPlugin.java:100)
    at it.auties.protobuf.serialization.ProtobufJavacPlugin.process (ProtobufJavacPlugin.java:88)

Please let me know if i am missing something while setup the environment or checkout the code; or guide me to compile the master or point me to right branch.

I request your help to compile the code to contribute at my best.

Thanks in advance.

**Comment by pcvarma-sayukth** [comment]
Hi [Auties00](Alessandro Autiero)
Looks like many *.java files missing in the master branch. We are not able to compile the master branch. Please guide us to get the latest code and compile to contribute.

Thank you.

**Comment by Auties00** [comment]
Fixed in 0.0.8!
